final_collections = [
    'proof-moonbirds',
    # 'cryptopunks', #No Floorprice
    'azuki',
    # 'coolpetsnft', #UNOPENED
    'impostors-genesis-aliens',
    'official-moar-by-joan-cornella',
    'mutant-ape-yacht-club',
    'boredapeyachtclub',
    'arcade-land',
    'los-muertos-world',
    'clonex',
    # 'beanzofficial', #UNOPENED
    'official-kreepy-club',
    'galverse',
    'hakinft-io',
    'hikarinftofficial',
    'shinsekai-portal',
    'tiny-dinos-eth',
    'premint-collector',
    'doodles-official',
    'sandbox',
    'froyokittenscollection',
    'cool-cats-nft',
    'rtfkt-mnlth',
    'milady',
    # 'akutar-mint-pass', #UNOPENED
    'proof-collective',
    'everai-heroes-duo',
    'alien-frens-evolution',
    'notbanksyechoes',
    'the-art-of-seasons',
    'nft-worlds',
    'vaynersports-pass-vsp',
    'veefriends',
    'cyberbrokers',
    # 'veefriends-series-2', #UNOPENED
    'thelobstars',
    'world-of-women-galaxy',
    'quirkiesoriginals',
    'adidasoriginals',
    # 'worldwidewebbland', #UNOPENED
    'bored-ape-kennel-club',
    'alienfrensnft',
    # 'quantum-access-pass', #UNOPENED
    'unemployables',
    'mfers',
    'akumaorigins',
    'the-picaroons',
    'toxic-skulls-club',
    # '0xogpass', #UNOPENED
    'bored-ape-chemistry-club',
    # 'art-blocks', #No Floorprice
    'monkey-legends',
    # 'bff-friendship-bracelets', #UNOPENED
    'megakongs',
    'the-artieverse',
    'gh0stlygh0sts',
    '3landers',
    'akistory',
    'world-of-women-nft',
    'friendsies',
    'llamaverse-genesis',
    'pudgypenguins',
    'cosmodinos-omega',
    'decentraland',
    'invisiblefriends',
    'illogics',
    'meebits',
    'killabears',
    'forest-spirits-zenft',
    'murakami-flowers-seed',
    '10ktf',
    'metroverse-blackout',
    'dennisrodmansbarbershop',
    'alien-frens-incubator',
    'gnssart',
    'cyber-factory-2',
    'karafuru',
    # 'baosociety-official', #UNOPENED
    'bobutoken',
    'antebellumgenesisland',
    'kureiji-nft-official',
    'acrocalypse',
    'mutantshibaclub',
    'gnssbymgxs',
    'zombieclub-token',
    'project-godjira-gen-2',
    'scottkelly',
    'ethlizards',
    'hausphases',
    'kiwami-genesis',
    'thehabibiz',
    'fewoworld-paint',
    'murixhaus',
    'elemental-fang-lijun',
    'oof-collective-official',
    'gutter-clones',
    'loser-club-official',
    # 'ghxsts-comics', #UNOPENED
    # 'gutter-juice', #UNOPENED
    'fortune-friends-club-official-nft',
    'projectnanopass',
    'forgottenruneswizardscult',
    # 'coniun-pass', #UNOPENED
    'the-sandbox-shibuya-land-sale',
    # 'the-seekers', # UNOPENED
    'metroverse-genesis',
    'hapeprime',
    'collectvoxthewalkingdead',
    'decentral-games-ice',
    'jpeg-cards',
    'alphasharksofficial',
    'nyokies',
    'genesis-creepz',
    'quackyducksofficial',
    # 'cyberronin-haruka', #UNOPENED
    'capsulehouse',
    'coolmans-universe',
    'cyberkongz',
    'kaiju-kingz',
    'cryptoadz-by-gremplin',
    'tubby-cats',
    # 'firstdayout', #UNOPENED
    'deadfellaz',
    'metakages-official-collection',
    'psychedelics-anonymous-genesis',
    'town-star',
    'veecon-tickets',
    '10ktf-stockroom',
    'lvcidiaavatars',
    # 'dennisrodmansbarbershopmint', #NO FP
    'neotokyo-citizens',
    'fidenza-by-tyler-hobbs',
    'g00p',
    'degentoonz-collection',
    'bossbeauties',
    'justcubesnft',
    'omni-mosquitoes-eth',
    'rtfkt-podx',
    'wolf-game',
    # 'huxley-comics', #UNOPENED
    'thewalkingdeadofficialdarylmotorcycles',
    # 'sunmiya-club-official', #NOT ETH,
    'bapetaverse-official',
    'mee6-avatars-pre-reveal',
    'rubberduckz',
    'nouns',
    'mv3-access-passes',
    'fluf-world',
    'chumchumsnft',
    'where-my-vans-go',
    'lazy-lions',
    'psychonautapedivision',
    'spaceridersnft',
    'bapetaverse-official',
    'the-squishiverse',
    # 'mirandus', #missing
    # 'the-meta-kongz',  #UNOPENED
    'etherthings',
    # 'space-boo-official-nft', #UNOPENED
    'officialkenkyo',
    'felinefiendznft',
    'women-unite-10k-assemble',
    # 'chromie-squiggle-by-snowfro', #missing
    'lilium',
    'pixel-interfaces',
    'mypethooligan',
    'shatteredeon-colonist',
    'frankfrank',
    'beari-collection',
    'crypto-unicorns-market',
    'max-pain-and-frens-by-xcopy',
    'pixel-vault-mintpass',
    'guttercatgang',
    'pjppfl',
    # 'clonex-mintvial', #UNOPENED
    'fools-nft',
    'notbanksyrain',
    'metahero-generative',
    'nifty-tailor-genesis-mintpass',
    'llamaboost',
    'headtripz',
    # 'syltare-dawn-of-east-klaytn', #NOT ETH
    'layer-zero-punks-eth',
    'pixels-farm',
    'dourdarcels',
    'cyberkongz-vx',
    'alphakongsclub',
    'mad-meerkat-burrow',
    # 'yakuza-pandas', #UNOPENED
    'treeverse',
    # 'retro-arcade-collection', #UNOPENED
    'moonbirdpunks',
    'grayboys',
    'theshiboshis',
    'smiliesgenesis',
    'fvck-avatar-essence',
    'space-doodles-official',
    'pet-rock',
    'chain-runners-nft',
    'smallbros',
    # 'lasercat-nft', #UNOPENED
    'raidparty',
    'mirlclub',
    'ballies',
    'mad-hare-society-2',
    'mad-hare-society-1',
    'frenlypandas',
]
